_p.cmd.bg_color("white")
_p.cmd.set("antialias",2)
#_p.cmd.set("ray_trace_mode",2)
_p.cmd.set("ray_opaque_background",0)
#_p.cmd.set("fog",0)
#_p.cmd.set("ambient",0.66)
#_p.cmd.set("reflect",0)
#_p.cmd.set("spec_reflect",0.08)
#_p.cmd.set("light_count", 2)
# cartoon representation
#_p.cmd.set("cartoon_oval_width", 0.46)
#_p.cmd.set("cartoon_oval_length", 1.35)
#_p.cmd.set("cartoon_loop_radius", 0.46)
#_p.cmd.set("cartoon_oval_quality", 25)
#_p.cmd.set("cartoon_loop_quality", 100)
_p.cmd.png("/test.png",ray=1)
_p.cmd.bg_color("black")
_p.cmd.set("antialias",0)
_p.cmd.set("ray_trace_mode",0)
_p.cmd.set("ray_opaque_background",0)
print("DONE")
